spring:
  application:
    name: investment-portfolio-manager


  #database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: portfolio_user
    password: your_password
    driver-class-name: org.postgresql.Driver
    hikari:
      # Connection pool settings (important for financial apps)
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  #JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop #creates tables automatically
      show-sql: true # shows SQL queries in console
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true # Makes SQL queries readable
          use_sql_comments: true
          jdbc:
            time_zone: IST # Important for financial timestamps
        open-in-view: false

  #Server configuration
  server:
    port: 8000
    servlet:
      context-path: /api #all endpoints will be /api/...

      # Logging Configuration (Professional setup)
      logging:
        level:
          com.snig.investment-portfolio-manager: DEBUG
          org.hibernate.SQL: DEBUG
          org.hibernate.type.descriptor.sql.BasicBinder: TRACE
          org.springframework.web: DEBUG
        pattern:
          console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
          file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
        file:
          name: logs/portfolio-manager.log

      # Custom Application Properties
      portfolio:
        # External API Configuration (for stock prices)
        api:
          alpha-vantage:
            api-key: ${ALPHA_VANTAGE_API_KEY:demo}  # We'll get a real key later
            base-url: https://www.alphavantage.co/query

        # Risk Calculation Settings
        risk:
          confidence-level: 0.95  # 95% confidence for VaR calculations
          lookback-days: 252      # 1 year of trading days for volatility

        # Portfolio Settings
        settings:
          max-positions-per-portfolio: 50
          min-cash-percentage: 5.0
          max-single-position-percentage: 20.0

      # Management Endpoints (for monitoring)
      management:
        endpoints:
          web:
            exposure:
              include: health,info,metrics
        endpoint:
          health:
            show-details: always

      # Development Profile Specific Settings
      ---
      spring:
        config:
          activate:
            on-profile: dev

        # Development database settings
        datasource:
          url: jdbc:postgresql://localhost:5432/portfolio_db_dev

        jpa:
          hibernate:
            ddl-auto: create-drop
          show-sql: true

      ---
      spring:
        config:
          activate:
            on-profile: prod

        # Production database settings (when we deploy)
        datasource:
          url: ${DATABASE_URL}
          username: ${DB_USERNAME}
          password: ${DB_PASSWORD}

        jpa:
          hibernate:
            ddl-auto: validate  # Never auto-create tables in production
          show-sql: false

        logging:
          level:
            com.snig.investment-portfolio-manager: INFO
            org.hibernate.SQL: WARN